"""
Django settings for my_django18_project project.

Generated by 'django-admin startproject' using Django 1.8.17.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
#from settings_secret import *
import datetime




BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
#C:\.virtualenvs\django18_project\src

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '3xzhjkgr@l!db8iuq%n8l)o8+dx6z-4mo3fb-lf7!(63mpm$ky'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#email credentials
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'yelikmelik@gmail.com'
EMAIL_HOST_PASSWORD = '' #os.environ['EMAIL_HOST_PASSWORD']
EMAIL_PORT = 587
EMAIL_USE_TLS = True
#amazonS3 credentials
AWS_ACCESS_KEY_ID = 'AKIAIO5J55CHPJYLADLQ' #os.environ['AWS_ACCESS_KEY_ID']
AWS_SECRET_ACCESS_KEY = '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' #os.environ['AWS_SECRET_ACCESS_KEY']
AWS_STORAGE_BUCKET_NAME = 'tawamazon'
STATICFILES_STORAGE = 'storages.backends.s3boto.S3BotoStorage'
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto.S3BotoStorage'
S3_URL = '//%s.s3.amazonaws.com/' % AWS_STORAGE_BUCKET_NAME
MEDIA_URL = S3_URL + 'media/'
STATIC_URL = S3_URL + 'static/'
ADMIN_MEDIA_PREFIX = STATIC_URL + 'admin/'
date_two_months_later = datetime.date.today() + datetime.timedelta(2 * 365 / 12)
expires = date_two_months_later.strftime('%A, %d %B %Y 20:00:00 GMT')
AWS_HEADERS = {
    'Expires': expires,
    'Cache-Control': 'max-age=86400',
}

#twitter credentials
twt_APP_KEY = 'mUEtXSXEFxQFpLHsSF55PCers' #os.environ['twt_APP_KEY']
twt_APP_SECRET = 'EwEhFr1cIVnhoGtJJj8GXX8ikWI8y1NUQGALnNYWnOWPvzCrP1' #os.environ['twt_APP_SECRET'] 
twt_OAUTH_TOKEN = '82124255-qYlivXrhohTDK3eiQkG4wvDVYuST9hcldN3wVJ3va' #os.environ['twt_OAUTH_TOKEN'] 
twt_OAUTH_TOKEN_SECRET = 'HFjPTOJRhiPT76jkm2XA4lBPS5Uk2ZEfvGm5OTfz41zAV' #os.environ['twt_OAUTH_TOKEN_SECRET'] 

#Mail credentials imported from settings_secret

# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'profiles',
    'crispy_forms',
    'registration',
    'storages',
    'rest_framework',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'my_django18_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ os.path.join(BASE_DIR, 'static', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'my_django18_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#    }
#}

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'django_db',
        'USER': 'localuser',
        'PASSWORD': 'local007',
        'OPTIONS': {'read_default_file': 'my.cnf'},
    }
}

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


##Static files (CSS, JavaScript, Images)
##https://docs.djangoproject.com/en/1.8/howto/static-files/
#MEDIA_URL = "/media/"
#MEDIA_ROOT = os.path.join(BASE_DIR, 'static', 'media')
##C:\.virtualenvs\django18_project\static\media
#
#STATIC_URL = '/static/'
#STATIC_ROOT = os.path.join(BASE_DIR, 'static', 'root')
##C:\.virtualenvs\django18_project\static\root
#STATICFILES_DIRS = (
    #os.path.join(BASE_DIR, 'static', 'static'),
    ##C:\.virtualenvs\django18_project\static\static
#)

if not DEBUG:
    try:
        import dj_database_url
    except:
        pass
    # Update database configuration with $DATABASE_URL.
    #DATABASES['default'] =  dj_database_url.config()
    DATABASES = { 'default': dj_database_url.config() }
    
    # Honor the 'X-Forwarded-Proto' header for request.is_secure()
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    # Allow all host headers
    ALLOWED_HOSTS = ['tossaword.com','www.tossaword.com']
    STATIC_ROOT = 'staticfiles'
    MEDIA_ROOT = 'mediafiles'
    STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
    #C:\.virtualenvs\django18_project\static\static
    )



SCORES_FOLDER = os.path.join(BASE_DIR, "static" )

#Crispy FORM TAGs SETTINGS
CRISPY_TEMPLATE_PACK = 'bootstrap3'


#DJANGO REGISTRATION REDUX SETTINGS
ACCOUNT_ACTIVATION_DAYS = 7
REGISTRATION_AUTO_LOGIN = True
SITE_ID = 1
LOGIN_REDIRECT_URL = '/'

